PAGE_URL="https://www.linkedin.com/login"
LOGIN_USERNAME = "username"
LOGIN_PASSWORD = "password"
EMAIL="email"
DATABASE="database"
DATABASE_NAME="hire"
DATABASE_JOBS="jobs"
PASSWORD="password"
USER_AVATAR = "/html/body/div[5]/header/div/nav/ul/li[6]/div/button"
JOBS = "//*[@id='global-nav']/div/nav/ul/li[3]/a"
LOCATION="//*[@aria-label='City, state, or zip code']"
JOBS_TITLE="//*[@aria-label='Search by title, skill, or company']"
JOBS_LINK = "//a[contains(@class, 'job-card-list__title--link')]"
LOGOUT = "/html/body/div[4]/div/div/div[2]/section/footer/button[2]"
JOBS_DESCRIPTION = "jobs-description__container"
JOB_TITLE="artdeco-entity-lockup__title"
JOBS_CRAWL="job-card-container--clickable"
JOBS_PROVIDER="artdeco-entity-lockup__subtitle"
JOBS_LOCATION="artdeco-entity-lockup__caption"
JOBS_SALARY="artdeco-entity-lockup__metadata"
